services:
  vite:
    build: .
    image: vite-js
    container_name: gameslibrary
    hostname: home
    ports:
      - "8001:80"
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
